# Copyright (c) 2025 https://github.com/rasmabayu. All rights reserved.
name: CI - Validate Manifests

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubeconform
        uses: actions/setup-kubeconform@v1
        with:
          version: '0.6.0'  # pin stable version

      - name: Validate manifests
        run: |
          echo "[*] Validating all YAML manifests"
          find manifests -type f \( -name "*.yaml" -o -name "*.yml" \) -print0 | xargs -0 kubeconform -schema-location default
          echo "[*] Validation completed"

