name: CI - Validate Manifests

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          KUBECONFORM_VERSION="0.6.0"  # pin a stable version
          curl -sSL -o kubeconform https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64
          chmod +x kubeconform
          sudo mv kubeconform /usr/local/bin/
          kubeconform version

      - name: Validate manifests
        run: |
          find manifests -type f -name '*.yaml' -print0 | xargs -0 -n1 kubeconform -schema-location default
